server:
  port: 9080
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/sharedb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  token:
     secret: SMIDA
     expired: 3600000

#SET TRUE FOR INSERTING TESTING DATA TO DATABASE (!)
sharedb: false
